---
- name: Request Inspection SQL Insert Management
  hosts: localhost
  roles:
      - sikim_piolink.wfk_test
  tasks:
      - name: Set Req sql Config
        pio_req_sql:
            host: "{{ host }}"
            port: "{{ port }}"
            username: "{{ username }}"
            password: "{{ password }}"
            app_name: ansible_test
            status: 1
            block: 0
            log: 0
...
