---
- name: Signature Management - Url
  hosts: localhost
  roles:
      - sikim.piolink.wfk_test
  tasks:
      - name: Set Signature
        pio_sig_up:
            host: "{{ host }}"
            port: "{{ port }}"
            username: "{{ username }}"
            password: "{{ password }}"
            app_name: ALL
            sig_list:
                - sig_id: "120100001"
                  sig_status: "2"
                - sig_id: "120100002"
                  sig_status: "2"
...
