---
- name: User Define Signature Management - Url
  hosts: localhost
  roles:
      - sikim_piolink.wfk_test
  tasks:
      - name: Set Signature
        pio_user_sig_up:
            host: "{{ host }}"
            port: "{{ port }}"
            username: "{{ username }}"
            password: "{{ password }}"
            app_name: ALL
            sig_class: sig_req_url
            sig_list:
                - sig_content: test1
                  sig_status: 1
                  sig_type: 1
                  sig_ko_desc: "ansible test1"
                - sig_content: test2
                  sig_status: 2
                  sig_type: 1
                  sig_ko_desc: "ansible test2"
...
